### ISSUE TITLE
ORM Public UI

### ISSUE THREAD

**Issue by rgoss** [cwbi-apps/access-request#1]
## Module Name
Regulatory

## Platform 1 repository link(s) - note if archive only
NA-Not Currently in P1

## Module Admin(s): name - username
Randal Goss - rgoss

## Contributors: name - username
Randal Goss - rgoss

## Additional requests / comments
Please just create a repo and I will push the code.

**Comment by willbreitkreutz** [comment]
@rgoss repository available at https://github.com/cwbi-apps/orm-public-ui
