### ISSUE TITLE
Project Location Management code migration request

### ISSUE THREAD

**Issue by michael-e-capozzi** [cwbi-apps/access-request#10]
## Module Name
Project Location Management

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/project_monitor
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/xstorm
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/usmart

## Module Admin(s): name - username
Ryan Crosby - @ryancrosby-cwbi
Charles Howe - @charles-p-howe
Mike Capozzi - @michael-e-capozzi

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/usmart
https://github.com/cwbi-apps/xstorm
https://github.com/cwbi-apps/project_monitor

@michael-e-capozzi  Repos are ready to go.
