### ISSUE TITLE
TOWS Domestic Processing (Waterborne Application for Report Processing - WARP) Code Migration

### ISSUE THREAD

**Issue by rcaud21** [cwbi-apps/access-request#11]
## Module Name
TOWS Domestic Processing Module AKA Waterborne Application for Report Processing (WARP)

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/WARP
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/warpcfdocker
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/warpbe
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/warpui

## Module Admin(s): name - username
Ryan Caudill - rcaud21
Justin Carlson - carlson3
Joshua McFarland - jmcfarland32

## Contributors (non-admin): name - username
John Dubberley
Jim Buskirk - jabuskirk
Mark Adkins - madkins37

**Comment by willbreitkreutz** [comment]
Hi @rcaud21 got the repos all set up and the admin team populated, you should be getting invites.  

@madkins we'll just need your employeer and location in your profile then we can add you to the org. (https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles)

Also, have John post a reply here when his account is ready to get added.

Thanks,
Will

**Comment by stevendriley** [comment]
@willbreitkreutz Can you add me to the list of admins on this one?

**Comment by rcaud21** [comment]
@willbreitkreutz @madkins37 has updated his profile to include employer and location.

**Comment by willbreitkreutz** [comment]
@stevendriley I can when you set your profile up per https://github.com/orgs/cwbi-apps/teams

**Comment by stevendriley** [comment]
Sorry, I think I’ve got the mandatory fields in now.

Respectfully,

Steven Riley

US Army Corps of Engineers
Navigation and Civil Works Decision Support Center (NDC)
https://www.iwr.usace.army.mil/
7701 Telegraph Road, Casey Building Room I-202
Alexandria, Virginia  22315
(703) 659-3097

***@***.***<https://www.iwr.usace.army.mil/About/Technical-Centers/NDC-Navigation-and-Civil-Works-Decision-Support/>

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 10:37 AM
To: cwbi-apps/access-request ***@***.***>
Cc: Riley, Steven D CIV USARMY CEIWR (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] TOWS Domestic Processing (Waterborne Application for Report Processing - WARP) Code Migration (Issue #11)


@stevendriley<Blockedhttps://github.com/stevendriley> I can when you set your profile up per https://github.com/orgs/cwbi-apps/teams<Blockedhttps://github.com/orgs/cwbi-apps/teams>
