### ISSUE TITLE
CPR - Climate Preparedness and Resilience

### ISSUE THREAD

**Issue by jamestgade** [cwbi-apps/access-request#12]
## Module
CPR - Climate Preparedness and Resilience
https://code.il2.dso.mil/platform-one/products/cwbi/cpr?sort=name_asc

## Repository Name(s) 

archive
bio
cal
cds
cercap
chat
climate.mil
craftqc
ctp
cwvat
cwvat_indicators
data_processing_scripts
dcp
deprecated_apps
ecb
flipl
gager
goat
htd
leaflet
nsd
portal
qst
roi
rsi
ryberg2022
SLAT
slatdata
slcc
SLT
smartmeter
tst
tst_v1
va
va2
va3
va4
va6
va7
Va8
wildfires
wowa

## Platform 1 or GitHub repository link(s) - note if archive only

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/archive

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/bio

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/cal

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/cds

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/cercap

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/chat

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/climate.mil

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/craftqc

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/ctp

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/cwvat

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/cwvat_indicators

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/data_processing_scripts

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/dcp

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/deprecated_apps

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/ecb

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/flipl

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/gager

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/goat

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/htd

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/leaflet

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/nsd

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/portal

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/qst

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/roi

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/rsi

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/ryberg2022

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/SLAT

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/slatdata

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/slcc

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/SLT

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/smartmeter

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/tst

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/tst_v1

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va2

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va3

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va4

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va6

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/va7

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/Va8

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/wildfires

https://code.il2.dso.mil/platform-one/products/cwbi/cpr/wowa

## Module Admin(s): name - username

msantmiller
marylee-morrison-bah
clinch-tyler
jamestgade
reynolds-david-bah
nlawrence-bah

## Contributors (non-admin): name - username

mcnguyen-bah
cholder-bah
aferguson-bah
bryantkp-bah
vanneste-kristen
marienicholls

**Comment by jamestgade** [comment]
Additional Contributors:

khaynes-bah
jcessna-bah

**Comment by willbreitkreutz** [comment]
Hi @jamestgade do you mind if we set up a chat to go over these, looking at the list, I'm wondering if these are all needed or could benefit from some clean-up.

i.e. 

> va
> va2
> va3
> va4
> va6
> va7
> Va8

Also, I've been having teams with really generic repo names (roi, ecb...) name-space them, like `climate-roi` or `climate-ecb` so they are more clear when looking at the organization as a whole.  In P1 we had the ability to see where repos were in the hierarchy, but since we're moving to a flatter model to increase visibility in CWBI it will get messy quick if we don't adjust a little bit.

Thanks, 
Will

**Comment by jamestgade** [comment]
Hi Will,

Do you have time this afternoon?  If so, what times work for you?

Thanks,
Jim Gade

From: Will Breitkreutz ***@***.***>
Sent: Friday, April 19, 2024 12:09 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Gade, James T CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] CPR - Climate Preparedness and Resilience (Issue #12)


Hi @jamestgade<Blockedhttps://github.com/jamestgade> do you mind if we set up a chat to go over these, looking at the list, I'm wondering if these are all needed or could benefit from some clean-up.

i.e.

va
va2
va3
va4
va6
va7
Va8

Also, I've been having teams with really generic repo names (roi, ecb...) name-space them, like climate-roi or climate-ecb so they are more clear when looking at the organization as a whole. In P1 we had the ability to see where repos were in the hierarchy, but since we're moving to a flatter model to increase visibility in CWBI it will get messy quick if we don't adjust a little bit.

Thanks,
Will

**Comment by willbreitkreutz** [comment]
I could do 2-2:30 or  3-3:30 central if either works

**Comment by willbreitkreutz** [comment]
Just to document, I'm going to 
* prepend `climate-` to each repo name
* deprecated_apps => move content to /archive
* tst_v1 => move to /archive
* lower-case / snake-case the names

**Comment by willbreitkreutz** [comment]
@jamestgade you're correct, P1 and Github are both IAL2 which means no CUI.

-Will

**Comment by jamestgade** [comment]
I should have my profile updated now.  I'll let the other folks know also.

**Comment by marienicholls** [comment]
I've updated my github profile.  Let me know if anything else is missing.

Thanks,
Marie

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 11:21 AM
To: cwbi-apps/access-request ***@***.***>
Cc: Nicholls, Marie CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] CPR - Climate Preparedness and Resilience (Issue #12)

**Comment by willbreitkreutz** [comment]
@marienicholls you should get an invite and be good to go

**Comment by nlawrence-bah** [comment]
Hello Will,

I have ensured the following accounts are updated per the user profile requirements: 

@nlawrence-bah
@mcnguyen-bah
@cholder-bah
@khaynes-bah
@jcessna-bah

Best,

Nick

**Comment by willbreitkreutz** [comment]
@nlawrence-bah and @jamestgade I think I've got invites out to everyone, let me know if there's anyone I missed.
