### ISSUE TITLE
Nav Apps (LPMS, DIS, NTNI, TOWS) Code Migration

### ISSUE THREAD

**Issue by stevendriley** [cwbi-apps/access-request#13]
## Module Name
Nav Apps

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/ndc-joint-reporting-project
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/tows-foreign
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/dis-2.0
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/national-waterway-network
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/ntni - ARCHIVE ONLY
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/ntni-2.0
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/wcs_database
https://code.il2.dso.mil/platform-one/products/cwbi/navigation/wcs_graphql_api

## Module Admin(s): name - username
Steven Riley - stevendriley
Ryan Caudill - rcaud21
Justin Carlson - carlson3
Joshua McFarland - jmcfarland32

**Comment by stevendriley** [comment]
Requesting GitHub IDs from contractors as contributors now.

**Comment by eprete** [comment]
Contributor Access needed for:

Elise Prete - eprete

**Comment by Chris-Dixon-Abt-Global** [comment]
Contributor access needed for: 
Chris-Dixon-Abt-Global 
andreasmaier-abt
Elisabeth-Ashley-Abt-Global
Justin-Eiler-Abt-Global
Jayanthivenkataraman
emsavelli

**Comment by rthadr** [comment]
@stevendriley @willbreitkreutz I have mirrored all repos described here. Once, new repos are created, I can sync them to github.

**Comment by willbreitkreutz** [comment]
I've created the repos and added team members, the following list need to update profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles:

@stevendriley 
@kconnors88 
@Elisabeth-Ashley-Abt-Global
@Justin-Eiler-Abt-Global

@rthadr can you add your employer info to your profile?

@andreasmaier-abt I dig your profile pic

**Comment by rthadr** [comment]
@willbreitkreutz Thanks. My profile is updated.

**Comment by kconnors88** [comment]
@willbreitkreutz Profile updated

**Comment by willbreitkreutz** [comment]
@kconnors88 you should get an invite shortly

**Comment by rthadr** [comment]
@willbreitkreutz I found 2 stragglers on Nav:

public-ntni
public-lpms

**Comment by rthadr** [comment]
@willbreitkreutz Can we also make the following repos? They were under the above tows-foreign link on OP:

wcs-census-processing
wcs-dock-receipts
wcs-docker-compose
wcs-foreign-api
wcs-foreign-dashboard
wcs-foreign
wcs-lloyds-ingestion
wcs-piers-ingestion
wcs-vessel-management-system

**Comment by rthadr** [comment]
@willbreitkreutz Also need one for lpms-2.0

**Comment by willbreitkreutz** [comment]
@rthadr can we move the additional repos to a new issue?  that way it's a little easier to track.  Thanks.

**Comment by willbreitkreutz** [comment]
@Michael-Duckworth-Abt-Global I can get you added once you add a non-default profile picture.

**Comment by Michael-Duckworth-Abt-Global** [comment]
@willbreitkreutz Sorry I missed your comment. I just updated my profile pic.
