### ISSUE TITLE
Archive Dam/Levee

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#17]
## Module Name
LST
LUT
LSHI
LSRI
LIS
NLD

## Platform 1 or GitHub repository link(s) - note if archive only
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/lsri
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/LST1
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/levee-inspection-system-old
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/risk-database-tool
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/national-levee-database/nld_i
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/LUT
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/LSHI
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/lshi-legacy
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/national-levee-database-and-national-inventory-of-dams-web-applications

## Module Admin(s): name - username
Charles Howe - charles-p-howe

**Comment by charles-p-howe** [comment]
Please consolidate

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 12:27 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Howe, Charles P CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] Archive Dam/Levee (Issue #17)


@charles-p-howe<Blockedhttps://github.com/charles-p-howe> would it make sense just to move these into a monorepo called dam-levee-safety-archive or something? rather than create individual repos?

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/dam-levee-safety-archive
