### ISSUE TITLE
Terns and Plovers

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#19]
## Module Name
TPDMS

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/environmental/terns-and-plovers

## Module Admin(s): name - username
Tyler Clinch - clinch-tyler
Charles Howe - charles-p-howe

**Comment by willbreitkreutz** [comment]
✔️
