### ISSUE TITLE
CWBI Hub

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#20]
## Module Name
CWBI Hub

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/shared-services/cwbi-hub

## Module Admin(s): name - username
Ryan Wolniak - rwolniak
Charles Howe - charles-p-howe

**Comment by willbreitkreutz** [comment]
✔️

**Comment by charles-p-howe** [comment]
Messed up, can you make one called legacy-cwbi-hub for the current one, will be archived later.
