### ISSUE TITLE
NLD/NID/LIS

### ISSUE THREAD

**Issue by aubben** [cwbi-apps/access-request#21]
## Module Name
NLD/NID/LIS

## Platform 1 or GitHub repository link(s) - note if archive only
LIS https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/levee-inspection-system
NID/NLD https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/nld-nid-monorepo

## Module Admin(s): name - username
Thad Riley (rthadr)
Brian Vanbockern (bvanbockern2)

## Contributors (non-admin): name - username
Michael Mueller (mmueller536)
Tyler Streu (Streudal)
Noel Desmeris (npd29)
Alex Ubben (aubben)

## Additional requests / comments
this can become a dam and levee safety group if needed. Currently NLD/NID are one repo and LIS is another repo. Thad will migrate the code once the new repos are ready.

**Comment by rthadr** [comment]
@aubben @willbreitkreutz I have mirrored both of these repos and am ready to sync to github when new repos are available.

I also grabbed the LSRI repo that Brian V. had me create.

**Comment by willbreitkreutz** [comment]
Hey @aubben just to confirm Brian's username, @bvanbockern shows up as him, but bvanbockern2 is just an empty profile

**Comment by willbreitkreutz** [comment]
@npd29 could you add your employer to your profile so I know I've got the right person, thanks.

**Comment by bvanbockern** [comment]
I updated my profile for bvanbockern2

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by willbreitkreutz** [comment]
@bvanbockern just add a pic and we're good to go with you 2.0

**Comment by willbreitkreutz** [comment]
@rthadr created /lsri wouldn't mind a more descriptive name, but there you go 😉

**Comment by rthadr** [comment]
@willbreitkreutz @bvanbockern @aubben These repos have been migrated here.
