### ISSUE TITLE
ORM code migration request

### ISSUE THREAD

**Issue by mark-english** [cwbi-apps/access-request#22]
## Module Name
ORM

## Platform 1 or GitHub repository link(s) - note if archive only
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/orm/archive_orm3
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/orm/archive_orm_prototype
ARCHIVE: https://code.il2.dso.mil/platform-one/products/cwbi/orm/archive_orm_version
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_baseline
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_data_change
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_data_request
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_product_assurance
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_prototype
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_sandbox 
https://code.il2.dso.mil/platform-one/products/cwbi/orm/orm_version

## Module Admin(s): name - username
Sam Angley - 		@smangley
Jon Blackburn - 	@zakariah1
Jeff Bryson - 		@jeff-bryson
Mike Capozzi - 	@michael-e-capozzi
Chris Conley - 	@christopher-c-conley
Don Dazey - 		@donald-dazey
Mark English -		@mark-english 
Jennifer Fox -		@jennifer-fox
Karen Hurd -		@karen-hurd
Praveen Kumar -	@praveen-r-kumar
Joice Kurian -		@joice-kurian
Ken Mendenhall - 	@kenneth-mendenhall
Hong-Tu Nguyen -	@hong-tu-nguyen
Guy Polin - 		@guy-polin
Pete Ryan -		@peterdryan
Shirley Sameshima -	@shirley-sameshima
Jamie Varga - 		@james-varga

**Comment by willbreitkreutz** [comment]
Hi @mark-english I've added the repos and created teams for access.  The following folks will need to update their profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles and then I can add them too.

@michael-e-capozzi
@christopher-c-conley
@donald-dazey
@jennifer-fox
@karen-hurd
@praveen-r-kumar
@joice-kurian
@hong-tu-nguyen
@guy-polin
@peterdryan
@shirley-sameshima
@james-varga

**Comment by mark-english** [comment]
@willbreitkreutz - I'm in cwbi-apps and I see the repos created.
I'm attempting to import from P1 using the "...or import code from another repository"

![image](https://github.com/cwbi-apps/access-request/assets/166639692/01092a90-7f14-49da-b8ed-630dd5065c4f)

When entering a repository name it tells me it already exists:

![image](https://github.com/cwbi-apps/access-request/assets/166639692/59aff53a-5263-492c-ba83-80959a6eb202)

Should I be doing this a different way?

I see the "Next Steps" instructions here:
https://github.com/cwbi-apps/access-request

But I'm not sure where I'm supposed to execute those commands.

**Comment by michael-e-capozzi** [comment]
[@willbreitkreutz](https://github.com/willbreitkreutz) I updated my profile

**Comment by willbreitkreutz** [comment]
@mark-english the import tool is limited to org owners and would create a new repo, that's why you're seeing the name conflict. 

The commands on the Next Steps section are meant to be run on the command line by a developer with a local working copy of the repository. Typically this would be a switch between pushing to the remote repository at P1 to pushing to GitHub instead, that's why the instructions have you rename your `origin` remote.

**Comment by willbreitkreutz** [comment]
@hong-tu-nguyen Got you added
@michael-e-capozzi You should be good to go too.

**Comment by christopher-c-conley** [comment]
@willbreitkreutz: I updated my profile.

**Comment by willbreitkreutz** [comment]
@christopher-c-conley you should get an invite

**Comment by guy-polin** [comment]
@willbreitkreutz

I have updated my profile and 2FA.

Guy Polin

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 3:12 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Polin, Guy F CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] ORM code migration request (Issue #22)


Hi @mark-english<Blockedhttps://github.com/mark-english> I've added the repos and created teams for access. The following folks will need to update their profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles<Blockedhttps://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles> and then I can add them too.

@michael-e-capozzi<Blockedhttps://github.com/michael-e-capozzi>
@christopher-c-conley<Blockedhttps://github.com/christopher-c-conley>
@donald-dazey<Blockedhttps://github.com/donald-dazey>
@jennifer-fox<Blockedhttps://github.com/jennifer-fox>
@karen-hurd<Blockedhttps://github.com/karen-hurd>
@praveen-r-kumar<Blockedhttps://github.com/praveen-r-kumar>
@joice-kurian<Blockedhttps://github.com/joice-kurian>
@hong-tu-nguyen<Blockedhttps://github.com/hong-tu-nguyen>
@guy-polin<Blockedhttps://github.com/guy-polin>
@peterdryan<Blockedhttps://github.com/peterdryan>
@shirley-sameshima<Blockedhttps://github.com/shirley-sameshima>
@james-varga<Blockedhttps://github.com/james-varga>

**Comment by james-varga** [comment]
Will
I have updated by profile and 2 factor authentication settings.
Jamie

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 3:12 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Varga, James M CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] ORM code migration request (Issue #22)


Hi @mark-english<Blockedhttps://github.com/mark-english> I've added the repos and created teams for access. The following folks will need to update their profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles<Blockedhttps://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles> and then I can add them too.

@michael-e-capozzi<Blockedhttps://github.com/michael-e-capozzi>
@christopher-c-conley<Blockedhttps://github.com/christopher-c-conley>
@donald-dazey<Blockedhttps://github.com/donald-dazey>
@jennifer-fox<Blockedhttps://github.com/jennifer-fox>
@karen-hurd<Blockedhttps://github.com/karen-hurd>
@praveen-r-kumar<Blockedhttps://github.com/praveen-r-kumar>
@joice-kurian<Blockedhttps://github.com/joice-kurian>
@hong-tu-nguyen<Blockedhttps://github.com/hong-tu-nguyen>
@guy-polin<Blockedhttps://github.com/guy-polin>
@peterdryan<Blockedhttps://github.com/peterdryan>
@shirley-sameshima<Blockedhttps://github.com/shirley-sameshima>
@james-varga<Blockedhttps://github.com/james-varga>

**Comment by karen-hurd** [comment]
Booz Allen Hamilton Internal

Will, I updated my profile and added 2FA.

Thanks,
Karen

From: Will Breitkreutz ***@***.***>
Sent: Monday, April 29, 2024 3:12 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Hurd, Karen [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [cwbi-apps/access-request] ORM code migration request (Issue #22)

Hi @mark-english I've added the repos and created teams for access. The following folks will need to update their profiles per https: //github. com/cwbi-apps/policies?tab=readme-ov-file#user-profiles and then I can add them too. @michael-e-capozzi


Hi @mark-english<https://urldefense.com/v3/__https:/github.com/mark-english__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwzKvLXks$> I've added the repos and created teams for access. The following folks will need to update their profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles<https://urldefense.com/v3/__https:/github.com/cwbi-apps/policies?tab=readme-ov-file*user-profiles__;Iw!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwcXxoOmw$> and then I can add them too.

@michael-e-capozzi<https://urldefense.com/v3/__https:/github.com/michael-e-capozzi__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwagjcY-c$>
@christopher-c-conley<https://urldefense.com/v3/__https:/github.com/christopher-c-conley__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwZJS3QJA$>
@donald-dazey<https://urldefense.com/v3/__https:/github.com/donald-dazey__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwlbhpkC4$>
@jennifer-fox<https://urldefense.com/v3/__https:/github.com/jennifer-fox__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwoVzAAfs$>
@karen-hurd<https://urldefense.com/v3/__https:/github.com/karen-hurd__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwHTB2v-U$>
@praveen-r-kumar<https://urldefense.com/v3/__https:/github.com/praveen-r-kumar__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwtt27xSE$>
@joice-kurian<https://urldefense.com/v3/__https:/github.com/joice-kurian__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwhtA8ak8$>
@hong-tu-nguyen<https://urldefense.com/v3/__https:/github.com/hong-tu-nguyen__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwU5POk48$>
@guy-polin<https://urldefense.com/v3/__https:/github.com/guy-polin__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwGISuTEQ$>
@peterdryan<https://urldefense.com/v3/__https:/github.com/peterdryan__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwiUktg2Y$>
@shirley-sameshima<https://urldefense.com/v3/__https:/github.com/shirley-sameshima__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwE9-hyeU$>
@james-varga<https://urldefense.com/v3/__https:/github.com/james-varga__;!!May37g!PL0_JIeo_t0nQOvjRRUyZ7EtRiXT9gk6U6tZ_ToQuURjhQ2UQVPuekFjJTLy-JCMJUVxdeW6WRUosbTwxgqNE1Q$>

**Comment by mark-english** [comment]
@willbreitkreutz  - It looks like there is a file limit size of 100MB at GitHub.  We have a repository "orm_data_change" that won't migrate because there are several files over that size limit. Do you have any guidance on handling repositories with large objects?

**Comment by donald-dazey** [comment]
@willbreitkreutz my account SHOULD be good.  Please add my account.

**Comment by shirley-sameshima** [comment]
@willbreitkreutz my profile has been updated. Please add my account.

**Comment by praveen-r-kumar** [comment]
Will,
FYI, I updated my profile and added 2FA. Thanks.

-Praveen

From: Shirley Sameshima ***@***.***>
Sent: Thursday, May 2, 2024 2:38 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Kumar, Praveen R CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] ORM code migration request (Issue #22)


@willbreitkreutz<Blockedhttps://github.com/willbreitkreutz> my profile has been updated. Please add my account.

**Comment by willbreitkreutz** [comment]
@james-varga, @joice-kurian, @guy-polin, @praveen-r-kumar and @donald-dazey I've added you, but could you update your employer to reflect your company name, not CRREL, thanks.

@shirley-sameshima, @karen-hurd you should get invites as well.

Thanks

**Comment by jennifer-fox** [comment]
@willbreitkreutz - I updated my profile and added 2FA.

**Comment by willbreitkreutz** [comment]
HI @jennifer-fox The only thing missing is a unique profile pic that's not the default Gravatar thing.

**Comment by jennifer-fox** [comment]
@willbreitkreutz - profile pic updated.

**Comment by willbreitkreutz** [comment]
awesome, thanks @jennifer-fox

**Comment by mark-english** [comment]
@willbreitkreutz 
It looks like @guy-polin is no longer in the cwbi-apps group. Maybe he was removed for not updating his employer to reflect your company name.  If so, he just made that update. Can you please add him back?

**Comment by mark-english** [comment]
@willbreitkreutz 
It looks like @praveen-r-kumar was also removed from cwbi-apps. Similarly, he has updated his profile to reflect company name. Can you please add him back to the cwbi-apps group?

**Comment by willbreitkreutz** [comment]
Hi @mark-english I thought I had sent @guy-polin an invite, must have missed him in the group, he and @praveen-r-kumar have pending invites now for ORM

<img width="486" alt="image" src="https://github.com/cwbi-apps/access-request/assets/2568631/3590c035-0ced-470a-aad3-e177a7497e9d">

Thanks,
Will
