### ISSUE TITLE
PlanUSACE Code Migration

### ISSUE THREAD

**Issue by Chris-Dixon-Abt-Global** [cwbi-apps/access-request#24]
## Module Name
PlanUSACE

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/planning/planusace  

## Module Admin(s): name - username
Erin Rooks - ErinRooks
Andreas Maier - andreasmaier-abt
Chris Dixon - Chris-Dixon-Abt-Global 
Justin Eiler - Justin-Eiler-Abt-Global

**Comment by willbreitkreutz** [comment]
Repo created, waiting on Justin's profile edits and Erin's username

**Comment by Chris-Dixon-Abt-Global** [comment]
@willbreitkreutz , do you have the link to the repo that you created?

**Comment by willbreitkreutz** [comment]
@Chris-Dixon-Abt-Global yeah, it's https://github.com/cwbi-apps/planusace. you should have gotten an invite in your e-mail

**Comment by Chris-Dixon-Abt-Global** [comment]
### @willbreitkreutz , Erin's username is now: ErinRooks . I've added this to the original ticket. I've asked her to add her photo to the profile per CWBI requirements. Thank you!

**Comment by Chris-Dixon-Abt-Global** [comment]
Thanks @willbreitkreutz . I did not receive an invite to either repo. I do not see either repo listed in my repos list on github either.

**Comment by willbreitkreutz** [comment]
@Chris-Dixon-Abt-Global  not sure why the e-mail didn't get through, if you go to https://github.com/cwbi-apps you should be prompted to accept the invite too.

**Comment by Chris-Dixon-Abt-Global** [comment]
I thought that I did accept the invite earlier; however, it looks like I may not have. I just did and got several automated emails letting me know you added me to these apps.

[A red and white logo  Description automatically generated]
Chris Dixon, AICP, PMP  |  Associate  |  He/Him/His
+1 303 381 8267

Abt Global  |  One Tabor Center, 1200 17th Street, 10th Floor, Denver, CO 80202
abtglobal.com<https://www.abtglobal.com/>  |  @abtglobalimpact
Abt Associates is now Abt Global

**Comment by willbreitkreutz** [comment]
Saw @Justin-Eiler-Abt-Global profile updates and invite sent.
