### ISSUE TITLE
EMS Project Migration

### ISSUE THREAD

**Issue by RyanHutchison** [cwbi-apps/access-request#25]
## EMS (Engineering Management System):

EMS React 
https://code.il2.dso.mil/platform-one/products/cwbi/ems/ems-react

EMS API 
https://code.il2.dso.mil/platform-one/products/cwbi/ems/ems-api

Gantt Export Service
new repo: ems-gantt-export-service
https://code.il2.dso.mil/platform-one/products/cwbi/ems/gantt-export-service

ems-api-listener - (Owner: Jon Blackburn @zakariah1)
https://code.il2.dso.mil/platform-one/products/cwbi/ems/ems-api-listener

DHTMLX Gantt 6.2.7 - ( Archive)
new repo: ems-dhtmlx-gantt-627
https://code.il2.dso.mil/platform-one/products/cwbi/ems/dhtmlx-gantt-627

Gantt Export Service Legacy - (Archive)
new repo: ems-gantt-export-service-legacy
https://code.il2.dso.mil/platform-one/products/cwbi/ems/gantt-export-service-legacy

Engineering Management System DB (Owner: Charles Howe @charles-p-howe)
https://code.il2.dso.mil/platform-one/products/cwbi/ems/eng-management-system-db

DHTMLX Gantt 6.2.7 Enterprise - (Archive)
new repo: ems-dhtmlx-gantt-6.2.7-enterprise
https://code.il2.dso.mil/platform-one/products/cwbi/ems/dhtmlx-gantt-6.2.7-enterprise

## Module Admins:
Ryan Hutchison - RyanHutchison
James Manzione - Jamesmanzione (I don't think he's part of the USACE Org, he just created the account, i believe i stressed 2fa as a requirement, he doesn't have a picture or any activity but I can verify that it is him.)

## Contributors: 
Any org member really, but specifically:

Ryan Wolniak - rwolniak
Jordan Taillon - jmtaillon
Charles Howe - charles-p-howe
Tyler Clinch - clinch-tyler
Jon Blackburn - zakariah1
Heather Godbey - heather-godbey

The above list covers all contractors / contributors past and present other than yourself. Apologies for showing up so late to the party, it was like pulling teeth to get some participants to activate.  It just makes everything stressful. If it's not mandatory for repos to be flat, using an EMS container wouldn't be terrible considering the amount of stuff in that case the old names would be fine. If flat though the new repo names will help identify the assets. Unsure how licensing will work on purchased library assets archives. I appreciate your assistance with this, apologies again for the short suspense stress.

**Comment by willbreitkreutz** [comment]
I've added the repos above. 

I changed eng-management-system-db to ems-db for consistency if that's ok, if not we can change it.

Once the code is pushed for the archive ones we can mark them as archived and lock them.

once @Jamesmanzione updates his profile per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles and then I'll get him added

**Comment by RyanHutchison** [comment]
@willbreitkreutz Not a problem at all. I appreciate your swift action on this and apologize for being so late. Will let you know once everything is pushed.

**Comment by willbreitkreutz** [comment]
Thanks @Jamesmanzione invite sent.

**Comment by RyanHutchison** [comment]
@willbreitkreutz I'm unsure if it's intentional or not, but I'm unable to change the default branch of the repositories under our control. Settings are extremely limited to Pages only, no other configuration settings. So it's coming up HEAD as the default branch, is this intentional? Should I be opening a new issue for things like this?

**Comment by willbreitkreutz** [comment]
@Jamesmanzione you migrate, but looks like you guys figured it out.  

@RyanHutchison The default branch should be set to `main`. You have `maintain` rights on the repo, there are some things that are locked out.  Let me know if there are things you need to change but can't.  You can e-mail me directly or just submit a new ticket in the access request repo.
