### ISSUE TITLE
REMIS-G

### ISSUE THREAD

**Issue by clinch-tyler** [cwbi-apps/access-request#27]
## Module Name
REMIS Geospatial

## Repository Name(s) - leave blank to use existing name from link below.
remis-g

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/infrastructure/remis

## Module Admin(s): name - username
Alicyn Hargroves: alicynh
Backup can be Tyler

## Contributors (non-admin): name - username
Tyler Clinch: clinch-tyler
Charles Howe: charles-p-howe

**Comment by willbreitkreutz** [comment]
Here you go https://github.com/cwbi-apps/remis-g
