### ISSUE TITLE
Template Generator Repo Request

### ISSUE THREAD

**Issue by ajbuchanjr** [cwbi-apps/access-request#29]
## Module Name
USACE Template Generator 

## Repository Name(s) - leave blank to use existing name from link below.
template-generator

## Module Admin(s): name - username
moosa-bah
arisSocorro
LSEETHALER 
Will add Dave Schaeffer but I don’t see his account

## Contributors (non-admin): name - username
ajbuchanjr

## Additional requests / comments
New repo request - USACE Template Generator that we are building with Dave Schaeffer. This will be a React front end with a .NET backend due to the need to integrate OpenXML to create templated Word Documents. This builds on the Python based USACE Template Generator that Dave created and is currently in the App Portal.

**Comment by willbreitkreutz** [comment]
@ajbuchanjr is for regulatory then?

**Comment by ajbuchanjr** [comment]
@willbreitkreutz Yes, Regulatory. So fine to create template-generator team under Regulatory team or however you want to do it.

**Comment by willbreitkreutz** [comment]
Cool, thanks.  Just trying to nest teams under the top level categories

**Comment by willbreitkreutz** [comment]
@ajbuchanjr here you go https://github.com/cwbi-apps/template-generator

Have Dave submit a member request issue when he signs up for Github, I couldn't find him with some cursory searching.
