### ISSUE TITLE
Risk Database Migration

### ISSUE THREAD

**Issue by aubben** [cwbi-apps/access-request#3]
## Module Name
Risk Database (Risk DB)

## Repository Name(s) - leave blank to use existing name from link below.
RiskDB

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/dam-and-levee-safety/riskdb

## Module Admin(s): name - username
aubben
gesamples
SAMease
bpcayton

## Additional requests / comments
new contractor is being onboarded - admins and contributors will be added once new contractor user accounts are created.

**Comment by willbreitkreutz** [comment]
@aubben we're going to use teams to organize permissions, do you want me to create a specific team for this app or would it make more sense to have "dam-and-levee-safety-admins" that can admin all the DLS repos?

**Comment by aubben** [comment]
@willbreitkreutz please organize teams by app as we have different contractors working on different apps.

**Comment by willbreitkreutz** [comment]
@aubben here you go: https://github.com/cwbi-apps/riskdb. 

I'll need bpcayton to update their profile then i can add them, same rules as in the USACE org, once he does go ahead and comment here and we can close the issue.

**Comment by willbreitkreutz** [comment]
@bpcayton let me know when you get a chance to update your profile per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles. Thanks

cc @aubben

**Comment by bpcayton** [comment]
Updated

Benjamin P. Cayton
Computer Scientist
Dam Safety Modification Center


***@***.***

Office 304.399.5130 / Mobile 304.638.9603
https://www.lrh.usace.army.mil/Missions/DSMMCX/
US Army Corps of Engineers, CELRH-MXM
502 Eighth Street
Huntington, WV 25701










From: Will Breitkreutz ***@***.***>
Sent: Tuesday, April 9, 2024 12:10 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Cayton, Benjamin P CIV (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] Risk Database Migration (Issue #3)


@bpcayton<Blockedhttps://github.com/bpcayton> let me know when you get a chance to update your profile per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles<Blockedhttps://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles>. Thanks

cc @aubben<Blockedhttps://github.com/aubben>

**Comment by willbreitkreutz** [comment]
@bpcayton you should be good to go now.

**Comment by aubben** [comment]
@willbreitkreutz can you please add new user svshephe1 as an admin for risk database?

**Comment by willbreitkreutz** [comment]
I can add @daleb77, but @svshephe1 will need to update their profile per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles then they will be good to go.

**Comment by svshephe1** [comment]
I updated my profile!

**Comment by willbreitkreutz** [comment]
Thanks @svshephe1, I'll add you but could you add your full name to the profile too, that is the only outstanding thing i caught, thanks in advance.

**Comment by svshephe1** [comment]
Ugh. How did I miss that? Fixed!
