### ISSUE TITLE
New Repository Request - Remaining Nav Apps (LPMS, NTNI, TOWS Foreign)

### ISSUE THREAD

**Issue by rthadr** [cwbi-apps/access-request#33]
## Module Name
Navigation

## Repository Name(s)
lpms-2.0
public-ntni
public-lpms
wcs-census-processing
wcs-dock-receipts
wcs-docker-compose
wcs-foreign-api
wcs-foreign-dashboard
wcs-foreign
wcs-lloyds-ingestion
wcs-piers-ingestion
wcs-vessel-management-system

## Should existing teams be leveraged for access? If so which?
Yes. The team created as part of #13 

## Admin(s): name - username
Steven Riley - stevendriley
Ryan Caudill - rcaud21
Justin Carlson - carlson3
Joshua McFarland - jmcfarland32

## Contributors (non-admin): name - username
CDM:
Katrina Connors Github ID: kconnors88
Thad Riley Github ID: @rthadr 
Elise Prete Github ID: eprete

ABT:
Chris-Dixon-Abt-Global
andreasmaier-abt
Elisabeth-Ashley-Abt-Global
Justin-Eiler-Abt-Global
Jayanthivenkataraman
emsavelli

**Comment by willbreitkreutz** [comment]
@rthadr you should be good to go, let me know if you run into something i missed
