### ISSUE TITLE
New Repository Request -

### ISSUE THREAD

**Issue by jayanthivenkataraman** [cwbi-apps/access-request#35]
## Should existing teams be leveraged for access? If so, which?
Yes, please use the same team as the ndc-joint-reporting-project for providing access with and that project resides in this repo: https://github.com/cwbi-apps/ndc-joint-reporting-project

## Admin(s): name - username
stevendriley

## Contributors (non-admin): name - username
Chris-Dixon-Abt-Global
andreasmaier-abt
Elisabeth-Ashley-Abt-Global
Justin-Eiler-Abt-Global
Jayanthivenkataraman
emsavelli

**Comment by willbreitkreutz** [comment]
HI @jayanthivenkataraman here you go: https://github.com/cwbi-apps/ndc-internal-and-external-splash-page let me know if there's anything I missed.
