### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by reynolds-david-bah** [cwbi-apps/access-request#39]
## Module Name
https://github.com/cwbi-apps/climate-tst

## Requests / comments
I'm unable to push to climate-tst since I don't have write permissions.

![Screenshot 2024-05-20 173835](https://github.com/cwbi-apps/access-request/assets/161879504/56c3f60d-5513-4fba-a1c5-de9b97dc25e6)

**Comment by willbreitkreutz** [comment]
@reynolds-david-bah looks like I missed some repos when setting permissions since there are so many climate ones, I didn't see the additional page, you should be good now.
