### ISSUE TITLE
PID code migration request

### ISSUE THREAD

**Issue by ryancrosby-cwbi** [cwbi-apps/access-request#4]
## Module Name
PID

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/pid/2101
https://code.il2.dso.mil/platform-one/products/cwbi/pid/briefing
https://code.il2.dso.mil/platform-one/products/cwbi/pid/cap
https://code.il2.dso.mil/platform-one/products/cwbi/pid/cwifd2
https://code.il2.dso.mil/platform-one/products/cwbi/pid/data_calls
https://code.il2.dso.mil/platform-one/products/cwbi/pid/ei_database
https://code.il2.dso.mil/platform-one/products/cwbi/pid/em
https://code.il2.dso.mil/platform-one/products/cwbi/pid/es_cwifd
https://code.il2.dso.mil/platform-one/products/cwbi/pid/home
https://code.il2.dso.mil/platform-one/products/cwbi/pid/prism
https://code.il2.dso.mil/platform-one/products/cwbi/pid/rec_cwifd

## Module Admin(s): name - username
Ryan Crosby - @ryancrosby-cwbi
Bryan Chau - @chaubryan
Tim Connally - @timothyconnally

## Contributors (non-admin): name - username
Osman Javaid - -user not created yet-

**Comment by willbreitkreutz** [comment]
Hey @ryancrosby-cwbi we're going to use teams to manage access, do you want a single team for admin and one for contributors across all the repos listed?

**Comment by ryancrosby-cwbi** [comment]
hey @willbreitkreutz ! Yes - that sounds logical to me. Thanks!

**Comment by willbreitkreutz** [comment]
@ryancrosby-cwbi do you mind if I prepend the repo names with PID so they are all kind of namespaced?  i.e. pid-home

**Comment by ryancrosby-cwbi** [comment]
sure. i liked the gitlab namespaces! assuming that doesn't exist here

**Comment by willbreitkreutz** [comment]
it's one of those things, we could separate out into separate orgs, but then visibility is limited, in order to maximize what everyone in cwbi can see (and keep my headaches minimal) we decided to keep everything flat

**Comment by willbreitkreutz** [comment]
<img width="1037" alt="image" src="https://github.com/cwbi-apps/access-request/assets/2568631/3108df5c-cae4-4199-bcca-bc7ac877cfbb">

**Comment by willbreitkreutz** [comment]
pid-admins are set up, will add access for pid-developers now

Once the other folks have their accounts set up have them add comments here and we'll add them

**Comment by timothyconnally** [comment]
Please add me to the pid-admins group - Thanks

**Comment by chaubryan** [comment]
Hi, Please add me (chaubryan) to the pid-admins group as well. Thanks in advance.

**Comment by willbreitkreutz** [comment]
Hi @timothyconnally  and @chaubryan please take a look at the profile requirements, once you're set up then we'll be good to go.  https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles
Thanks

**Comment by timothyconnally** [comment]
@willbreitkreutz I added Name, Business, Location, Picture (icon) and 2FA to my profile.  Those were listed as required.  Please let me know if I need to update anything else.  Thanks.

**Comment by chaubryan** [comment]
Hi Will,

I’ve added Name, Business, Location, Picture (icon) and 2FA to my profile. Please let me know if I need to update anything else.

Thanks,

Bryan
From: Will Breitkreutz ***@***.***>
Sent: Thursday, April 4, 2024 1:57 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Chau, Bryan CTR USARMY CEERD-CRREL (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] PID code migration request (Issue #4)


@timothyconnally<Blockedhttps://github.com/timothyconnally> you're good to go. thanks

**Comment by willbreitkreutz** [comment]
@chaubryan you're good to go, thanks

**Comment by ryancrosby-cwbi** [comment]
@willbreitkreutz when you get a chance, could you make me a maintainer for the repo below?  I currently only have READ access and so cannot migrate it. thanks!

https://github.com/cwbi-apps/pid-ei-database

**Comment by willbreitkreutz** [comment]
@ryancrosby-cwbi must have missed a click, you should be good to go now.
