### ISSUE TITLE
New Repository Request - NDC Public Reporting

### ISSUE THREAD

**Issue by Chris-Dixon-Abt-Global** [cwbi-apps/access-request#44]
## Module Name
NDC Public Reporting

## Repository Name(s)
ndc-public-reporting

## Should existing teams be leveraged for access? If so which?
Yes, use this team:
nav-apps-developers  :  https://github.com/orgs/cwbi-apps/teams/nav-apps-developers

## Admin(s): name - username
Steven Riley:  stevendriley

## Contributors (non-admin): name - username
Justin Eiler: Justin-Eiler-Abt-Global
Chris Dixon: Chris-Dixon-Abt-Global

## Additional requests / comments
None

**Comment by Chris-Dixon-Abt-Global** [comment]
@willbreitkreutz , is there a chance this repo could be created soon so that we can get a code scan completed? Thanks Will! We would have created this repo sooner, but we thought that we could piggy back on another repo until this past Tuesday when we realized that we had to make a new one to maintain our history of code updates.

**Comment by willbreitkreutz** [comment]
@Chris-Dixon-Abt-Global sorry, i didn't see this one, i need to set it up to auto-assign me so i get a notification.

Repo is up and available: https://github.com/cwbi-apps/ndc-public-reporting

**Comment by Chris-Dixon-Abt-Global** [comment]
perfect. Thanks @willbreitkreutz
