### ISSUE TITLE
New Repository Request - RRS

### ISSUE THREAD

**Issue by abaghum** [cwbi-apps/access-request#49]
## Module Name
Regulatory Request System

## Repository Name(s)
RRS
RRS-Oracle

## Admin(s): name - username
Andranik Baghumyan - username: abaghum (For RRS)
Karen Hurd - username: karen-hurd (For RRS-Oracle)

**Comment by willbreitkreutz** [comment]
@abaghum do you want separate teams for managing access between `rrs` and `rrs-oracle`, or will one admin team across repos work?

**Comment by abaghum** [comment]
Separate teams. I want to be admin for RRS repo and Karen should be admin on RRS-Oracle repo.

**Comment by willbreitkreutz** [comment]
@abaghum, @karen-hurd repos are available at

https://github.com/cwbi-apps/rrs
https://github.com/cwbi-apps/rrs-oracle
