### ISSUE TITLE
ULA code migration request

### ISSUE THREAD

**Issue by ryancrosby-cwbi** [cwbi-apps/access-request#5]
## Module Name
ULA

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/ula/asur_fem
https://code.il2.dso.mil/platform-one/products/cwbi/ula/persapp
https://code.il2.dso.mil/platform-one/products/cwbi/ula/qldms
https://code.il2.dso.mil/platform-one/products/cwbi/ula/smd
https://code.il2.dso.mil/platform-one/products/cwbi/ula/transportation
https://code.il2.dso.mil/platform-one/products/cwbi/ula/ula_portal
https://code.il2.dso.mil/platform-one/products/cwbi/ula/ula_training

## Module Admin(s): name - username
Ryan Crosby - @ryancrosby-cwbi
Charles Howe - @charles-p-howe
Mike Capozzi - @michael-e-capozzi

## Additional requests / comments
Will add admins/contributors as they create accounts.

**Comment by michael-e-capozzi** [comment]
Please add these also
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/project_monitor
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/xstorm
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/usmart

**Comment by willbreitkreutz** [comment]
@michael-e-capozzi are these part of the ULA apps?  We're using teams to manage access so need to know how that should be set up.  if these are separate please submit a separate issue so I can track them, thanks.

**Comment by michael-e-capozzi** [comment]
I split it out to new issue 
https://github.com/cwbi-apps/access-request/issues/10
