### ISSUE TITLE
New Repository Request - CRAFT

### ISSUE THREAD

**Issue by mattsibcerl** [cwbi-apps/access-request#50]
## Module Name
sustainability

## Repository Name(s)
craft

## Admin(s): name - username
mattsibcerl

## Contributors (non-admin): name - username
KYThompson

**Comment by willbreitkreutz** [comment]
Hi @mattsibcerl and KYThompson, I'm getting the repo set up, if you could both set up your profiles per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles I'll get you added.

**Comment by mattsibcerl** [comment]
I updated mine.

@KYThompson make sure your profile is set up: 
https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles

**Comment by KYThompson** [comment]
I will update it now!


From: Matt Sibenaller ***@***.***>
Sent: Tuesday, June 18, 2024 3:01 PM
To: cwbi-apps/access-request ***@***.***>
Cc: Thompson, Kathryn Y CIV (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] New Repository Request - CRAFT (Issue #50)


I updated mine.

@KYThompson<Blockedhttps://github.com/KYThompson> make sure your profile is set up:
https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles<Blockedhttps://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles>

**Comment by willbreitkreutz** [comment]
Thanks @mattsibcerl and @KYThompson, invites should be in the mail
