### ISSUE TITLE
New Repository Request - approve/deny interface

### ISSUE THREAD

**Issue by Michael-Duckworth-Abt-Global** [cwbi-apps/access-request#51]
## Module Name

NCS Approve/Deny Interface

## Repository Name(s)

approvedenyinterface (can use "adi" if this is too long)

## Should existing teams be leveraged for access? If so which?

Yes, use this team:
nav-apps-developers : https://github.com/orgs/cwbi-apps/teams/nav-apps-developers

## Admin(s): name - username

Steven Riley: stevendriley

## Contributors (non-admin): name - username

Michael Duckworth: Michael-Duckworth-Abt-Global
Justin Eiler: Justin-Eiler-Abt-Global
Emily Savelli: emsavelli
Andreas Maier: andreasmaier-abt

## Additional requests / comments

none

**Comment by Michael-Duckworth-Abt-Global** [comment]
@willbreitkreutz What do module names correspond to?

**Comment by willbreitkreutz** [comment]
@Michael-Duckworth-Abt-Global here you go https://github.com/cwbi-apps/approvedenyinterface

**Comment by Michael-Duckworth-Abt-Global** [comment]
Thanks, Will!

Best,
Mike
________________________________
