### ISSUE TITLE
RRS repo permissions/settings

### ISSUE THREAD

**Issue by abaghum** [cwbi-apps/access-request#52]
## Module Name
rrs

## Requests / comments
I am an admin on this repo, but I do not have access to the "Code and automation" or "Access -> Collaborations and teams" under settings so I can add and/or remove team members. 
![github](https://github.com/cwbi-apps/access-request/assets/107516386/019e38ce-e818-4684-b27e-6843f72a8069)

**Comment by willbreitkreutz** [comment]
Let's give this a try. I've set you up to own the team for access, don't add anyone individually to the repo, just to the team(s).  The main reason we've restricted this so far is that we pay for each seat and only have a set number, so was trying to keep track of how many get assigned.  Please make sure anyone you add meets the profile requirements in https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles.  I've also set the admin team as owner on the repo so you should be able to alter the branch settings.

**Comment by abaghum** [comment]
Sounds good. Looks like those options are enabled in the settings now. Thank you
