### ISSUE TITLE
New Member Request 

### ISSUE THREAD

**Issue by abaghum** [cwbi-apps/access-request#53]
## Module Name(s)
CWBI-apps

## Member Name (name - username)
Chris Mitchell - ChrisMitchell33
Lezotte Eric - elezotte-bah
John (Jack) Taylor - jack-taylor-nh
Jazlene Rae Guevarra - jguevarra
Sean Kraus - seankraus1
Dave Walker - walker-david2
Ryan Tober - RJTober

## Additional requests / comments
For the whole team to have access to cwbi-apps.

**Comment by willbreitkreutz** [comment]
@abaghum should these folks be on the rrs developers team?

**Comment by abaghum** [comment]
Not all of them are developers so they will have different roles and permissions. Once they get added to the cwbi-apps I can added them to rrs.

**Comment by willbreitkreutz** [comment]
Ah, ok.

All are added except the following who need to update profiles:
elezotte-bah, walker-david2

@seankraus1, could you add BAH - USACE as your employer since you're technically BAH, just trying to make sure we keep track.

**Comment by abaghum** [comment]
ok I will ask them to fix it now.

**Comment by abaghum** [comment]
elezotte-bah, walker-david2 have updated their profiles.

**Comment by willbreitkreutz** [comment]
Invites in the mail, thanks.
