### ISSUE TITLE
New Repository Request - FREEBOARD

### ISSUE THREAD

**Issue by craigrthunter** [cwbi-apps/access-request#54]
## Module Name
FREEBOARD

## Repository Name(s)
FREEBOARD

## Admin(s): name - username
jameswestman-work

## Contributors (non-admin): name - username
darklordgrep
craigrthunter

**Comment by willbreitkreutz** [comment]
@craigrthunter I've set up the repo and added you and james.

@darklordgrep could you update your profile to include your employer per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/FREEBOARD

**Comment by darklordgrep** [comment]
Employer added.
Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Jun 26, 2024 at 9:40 AM, Will ***@***.***> wrote:   


@craigrthunter I've set up the repo and added you and james.

@darklordgrep could you update your profile to include your employer per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles

**Comment by willbreitkreutz** [comment]
@darklordgrep thanks!
