### ISSUE TITLE
New Repository Request - NDC AIS API

### ISSUE THREAD

**Issue by Michael-Duckworth-Abt-Global** [cwbi-apps/access-request#56]
## Module Name
NDC AIS API

## Repository Name(s)
ais-api

## Should existing teams be leveraged for access? If so which?
no

## Admin(s): name - username
Steven Riley: stevendriley

## Contributors (non-admin): name - username
Michael Duckworth: Michael-Duckworth-Abt-Global
Justin Eiler: Justin-Eiler-Abt-Global
Emily Savelli: emsavelli
Andreas Maier: andreasmaier-abt

## Additional requests / comments
none

**Comment by willbreitkreutz** [comment]
@Michael-Duckworth-Abt-Global do you mind if we call the repo `ndc-ais-api`?  The other NDC repos are name-spaced like that to make them easier to find, AIS is a pretty nebulous acronym.

**Comment by Michael-Duckworth-Abt-Global** [comment]
@willbreitkreutz Can we call it "ndc-ais-automatedvesseltrips"? Thanks.

**Comment by willbreitkreutz** [comment]
@Michael-Duckworth-Abt-Global should be good to go https://github.com/cwbi-apps/ndc-ais-automatedvesseltrips
