### ISSUE TITLE
New Member Request - fejnamhe for SDSFIE Portal

### ISSUE THREAD

**Issue by ajbuchanjr** [cwbi-apps/access-request#59]
## Module Name(s)
SDSFIE

## Member Name (name - username)
fejnamhe

## Teams / Repositories where access is needed
https://github.com/cwbi-apps/sdsfie-portal

**Comment by willbreitkreutz** [comment]
@fejnamhe, please populate your profile per https://github.com/cwbi-apps/policies?tab=readme-ov-file#user-profiles then I can set you up. Thanks

**Comment by willbreitkreutz** [comment]
ping @fejnamhe and @ajbuchanjr

**Comment by fejnamhe** [comment]
Sorry about the delay, Will. I think my profile is now set up correctly.  -Jeff


Jeff Ehman, PhD

Director of Geospatial Operations, Image Matters LLC

***@***.******@***.***>

812-325-7937



________________________________

**Comment by willbreitkreutz** [comment]
looks good, thanks @fejnamhe
