### ISSUE TITLE
CPN Legacy

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#6]
## Module Name
CPN

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/project-location-management/CPN

## Module Admin(s): name - username
Alicyn Hargroves: No username currently
Backup can be Charles
## Contributors (non-admin): name - username
Tyler Clinch: clinch-tyler
Charles Howe: charles-p-howe

## Additional requests / comments
This will most likely be archived in future, if it will conflict with the new CPN, this repo can be renamed to CPN-Legacy or applicable name.

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/cpn-legacy created

Have Alicyn comment here with her username and I'll add her to the team and close the request.
Thanks

**Comment by willbreitkreutz** [comment]
Closing to clean up the list, When Alicyn creates an account she can submit another ticket for access.
