### ISSUE TITLE
New Member Request -

### ISSUE THREAD

**Issue by timbbaldwin** [cwbi-apps/access-request#60]
## Module Name(s)
Pacific Northwestern Division Hydrology Portal

## Member Name (name - username)
Tim Baldwin - timbbaldwin

## Teams / Repositories where access is needed
Pacific Northwestern Division Hydrology Portal (new team)

**Comment by willbreitkreutz** [comment]
@timbbaldwin I've created the team and added you and Michael as admins, but will need to know what repos need to be created.
Thanks

**Comment by mkoohafkan** [comment]
See https://github.com/cwbi-apps/access-request/issues/61#issuecomment-2231776522 for list of repositories to be created. Note that with the exception of "crb-watplotter-image", all listed repos are standalone R packages. Please let me know if those should be hosted elsewhere (e.g. the [USACE ](https://github.com/USACE/) Github org).
