### ISSUE TITLE
New Member Request - Michael Koohafkan

### ISSUE THREAD

**Issue by mkoohafkan** [cwbi-apps/access-request#61]
## Module Name(s)
Pacific Northwestern Division Hydrology Portal

## Member Name (name - username)
Michael Koohafkan - @mkoohafkan

## Teams / Repositories where access is needed
Pacific Northwestern Division Hydrology Portal (requested in #60)

## Additional requests / comments
Hoping we will have permission to create our own repositories within our Team.

**Comment by willbreitkreutz** [comment]
@mkoohafkan right now repo creation is limited to org admins.  If you have a list of the repos needed we can get them set up.

**Comment by mkoohafkan** [comment]
Thanks, please create the following repositories:

- crb-watplotter-image
- watplotter.core
- watplotter.gui
- watplotter.batch
- watplotter.db
- watplotter.realtime
- watplotter.io
- watplotter.analysis

**Comment by willbreitkreutz** [comment]
@mkoohafkan I've got the repos set up and assigned to the team.  We'll keep them all here rather than try to put some in /USACE.  Do you want any to be public?  by default we set up repos with internal visibility, all members of the org can see them, but only the team has edit rights.

**Comment by mkoohafkan** [comment]
Thanks, all the `watplotter.*` repos can be public since we may have users of those R packages that don't necessarily need to be members of cwbi-apps. `crb-watplotter-image` should always be private though.

**Comment by mkoohafkan** [comment]
Can you give me admin access to my own repos? thanks!

**Comment by willbreitkreutz** [comment]
@mkoohafkan by policy we limit permissions to maintain for most users. what admin features were you needing to use?

**Comment by mkoohafkan** [comment]
having the ability to switch default branches and archive repositories, but there may be other permissions issues that I will encounter in the future. My understanding is that Github permissions are granular enough to provide me with admin rights to my own repositories without expanding my access rights to the entire organization.

What is the reason for preventing admin access at the individual repository level?

**Comment by mkoohafkan** [comment]
Any updates on this? Are you able to provide me with admin access to my own projects?

**Comment by willbreitkreutz** [comment]
We're still evaluating the issue, the permissions model isn't actually very granular and there are a number of admin permissions that have access-control and possible cost implications.  I'll let you know when we decide.  In the meantime i can update default branches

**Comment by mkoohafkan** [comment]
thanks, not having full control over my own projects is a showstopper for me so if that is not possible then please just delete all of the requested repositories except for `crb-watplotter-image`. We have other git hosting solutions available within NWD that provide a full feature set, the only draw for using this platform was to facilitate collaboration with CRREL for app building and sharing code between CorpsNet and non-CorpsNet machines.

**Comment by mkoohafkan** [comment]
Hi there, please delete the repositories:
- crb-watplotter-image
- watplotter.core
- watplotter.gui
- watplotter.batch
- watplotter.db
- watplotter.realtime
- watplotter.io
- watplotter.analysis

We have decided to go in a different direction for our hosting needs.

**Comment by willbreitkreutz** [comment]
Ok, sounds good
