### ISSUE TITLE
CWBI Airflow

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#7]
## Module Name
CWBI Airflow

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/cwbi-airflow-docker

## Module Admin(s): name - username
Charles Howe - charles-p-howe
Ryan Wolniak - rwolniak

## Additional requests / comments
The name for this module is bad, rename to CWBI Data Migration, or something less generic?

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/cwbi-data-migration created
