### ISSUE TITLE
New Member Request - CWBI DEV

### ISSUE THREAD

**Issue by Clayton-Thurmer-USACE** [cwbi-apps/access-request#73]
## Module Name(s)
CWBI DEV

## Member Name (name - username)
Clayton Thurmer - Clayton-Thurmer-USACE

## Teams / Repositories where access is needed
CWBI DEV

## Additional requests / comments
Will need a new repo/project for J-sheet AI project

**Comment by willbreitkreutz** [comment]
Hi @Clayton-Thurmer-USACE, your invite should be on it's way, and there's a fresh repo for you at https://github.com/cwbi-apps/j-sheet-ai
