### ISSUE TITLE
NWPL

### ISSUE THREAD

**Issue by charles-p-howe** [cwbi-apps/access-request#8]
## Module Name
National Wetland Plat List

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/regulatory/nwpl/nwpl

## Module Admin(s): name - username
Lyle Seethaler - LSEETHALER

## Contributors (non-admin): name - username
Charles Howe - charles-p-howe

**Comment by willbreitkreutz** [comment]
https://github.com/cwbi-apps/nwpl created
