### ISSUE TITLE
Create Enterprise Management Tool repository

### ISSUE THREAD

**Issue by DianaHallman** [cwbi-apps/access-request#81]
Please create a repository for the Enterprise Management Tool. Documentation is found in Confluence here:

Budget Management > Enterprise Management Tool (EMT)

Thank you,
Diana Hallman

**Comment by DianaHallman** [comment]
Module Name
Enterprise Management Tool (EMT)

Repository Name(s)

Should existing teams be leveraged for access? If so which?

Admin(s): name - username
Diana Hallman
Jennifer Hallman

Contributors (non-admin): name - username
Kevin Markey

**Comment by willbreitkreutz** [comment]
repo created here: https://github.com/cwbi-apps/emt
