### ISSUE TITLE
Create Planner Database repository

### ISSUE THREAD

**Issue by DianaHallman** [cwbi-apps/access-request#82]
Please create a Planner Database repository. Planner Database documentation is found in Confluence here:

Planning > Planner Database (SME)

Thank you,
Diana Hallman

**Comment by DianaHallman** [comment]
Module Name
Planner Database (SME)

Repository Name(s)

Should existing teams be leveraged for access? If so which?

Admin(s): name - username
Diana Hallman
Jennifer Hallman

Contributors (non-admin): name - username
Kevin Markey

**Comment by willbreitkreutz** [comment]
repo available here: https://github.com/cwbi-apps/sme
