### ISSUE TITLE
New Repository Request - LCET

### ISSUE THREAD

**Issue by aubben** [cwbi-apps/access-request#88]
## Module Name
Levee Cost Estimating Tool

## Repository Name(s)
LCET

## Should existing teams be leveraged for access? If so which?
Dam and Levee Safety (will add new members to team)

## Admin(s): name - username
bpcayton
gesamples
Prototroid

 

## Contributors (non-admin): name - username
aubben
SAMease

**Comment by willbreitkreutz** [comment]
@aubben here you go: https://github.com/cwbi-apps/lcet
