### ISSUE TITLE
New Repository Request - encroachment-permit-database-v2

### ISSUE THREAD

**Issue by steve-motoike** [cwbi-apps/access-request#97]
## Module Name
Encroachment Permit Database

## Repository Name(s)
encroachment-permit-database-v2

## Should existing teams be leveraged for access? If so which?
Yes. encroachment-permit-database

## Admin(s): name - username
steve-motoike
vtieu-gei
mmoua-gei
dreina-gei

## Additional requests / comments
Repo for the modernization of the existing application. Talked to the PMO/Chad and they requested that we setup a separate REPO for the modernization effort. I hope I filled out the Admin portion correctly. The team for this REPO will have the same members as the current REPO.

**Comment by steve-motoike** [comment]
Ooo... now that I'm looking at this again, I think didn't identify the existing team correctly. Maybe this one instead? 

encroachment-permit-database-admins

**Comment by willbreitkreutz** [comment]
Here you go @steve-motoike : https://github.com/cwbi-apps/encroachment-permit-database-v2

**Comment by steve-motoike** [comment]
Thank you!

S-

Steve Motoike
Electrical Engineer
US ARMY CORPS OF ENGINEERS, SACRAMENTO DISTRICT
ENGINEERING SUPPORT BRANCH
(CESPK-EDS)

1325 J Street, Sacramento, CA 95814
(916) 557-7042 (office)
(916) 709-1162 (mobile)
***@***.******@***.***>

From: Will Breitkreutz ***@***.***>
Sent: Tuesday, December 10, 2024 9:35 AM
To: cwbi-apps/access-request ***@***.***>
Cc: Motoike, Stephen S (Steve) CIV USARMY CESPK (USA) ***@***.***>; Mention ***@***.***>
Subject: [Non-DoD Source] Re: [cwbi-apps/access-request] New Repository Request - encroachment-permit-database-v2 (Issue #97)


Here you go @steve-motoike<BLOCKEDhttps://github.com/steve-motoike> : https://github.com/cwbi-apps/encroachment-permit-database-v2<BLOCKEDhttps://github.com/cwbi-apps/encroachment-permit-database-v2>
